---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: neo4j-2
  name: neo4j-2
spec:
  ports:
    -
      name: cluster
      port: 5001
      targetPort: 5001
    -
      name: cluster-secure
      port: 5002
      targetPort: 5002
    -
      name: transaction
      port: 6001
      targetPort: 6001
    -
      name: transaction-secure
      port: 6002
      targetPort: 6002
  selector:
    name: neo4j-2
