---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: neo4j-3
  name: neo4j-3
spec:
#  strategy: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      name: neo4j-3
  template:
    metadata:
      labels:
        name: neo4j-3
        app: neo4j
    spec:
      nodeSelector:
       failure-domain.beta.kubernetes.io/zone: eu-west-1a
      containers:
        -
          imagePullPolicy: Always
          image: rebelastronaut/neo4j-kubernetes:v0.0.1
          name: neo4j-3
          resources:
            limits:
              memory: "2G"
#              cpu: "100m"
          ports:
          - containerPort: 7474
            name: "http"
          - containerPort: 5002
            name: "cluster-secure"
          - containerPort: 6002
            name: "data-secure"
          env:
          - name: "NEO4J_dbms_mode"
            value: "HA"
    #      - name: NEO4J_AUTH
    #        value: "none"
          - name: NEO4J_ha_host_coordination
            value: 127.0.0.1:5001
          - name: NEO4J_ha_host_data
            value: 127.0.0.1:6001
          - name: "NEO4J_HA_ADDRESS"
            value: "0.0.0.0"
          - name: "NEO4J_ha_serverId"
            value: "3"
          - name: "NEO4J_ha_initialHosts"
            value: "https://neo4j-1:5002,https://neo4j-2:5002,https://neo4j-3:5002"
  #        volumeMounts: 
  #        - name: data
  #          mountPath: /var/lib/neo4j/data
  #        readinessProbe:
  #          httpGet:
  #            path: /
  #            port: 7474
  #          initialDelaySeconds: 30
  #          timeoutSeconds: 2 
          livenessProbe:
            httpGet:
              path: /
              port: 7474
            initialDelaySeconds: 30
            timeoutSeconds: 2 
      restartPolicy: Always
      volumes:
      - name: data
        # This AWS EBS volume must already exist.
        awsElasticBlockStore:
          volumeID: vol-b9a71a7c
          fsType: ext4
